name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  
                    
      - name: Move build results using rsync
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SOURCE: ./dist
          TARGET: ~/swim/web
          ARGS: -hvrPt
        
